apiVersion: v1
kind: Service
metadata:
  name: netflix-service
spec:
  selector:
    app: netflix-app
  type: LoadBalancer  # This will provision an external IP
  ports:
    - protocol: TCP
      port: 80          # Accessible port in browser
      targetPort: 3000  # Container port
