apiVersion: v1
kind: Service
metadata:
  name: netflix-service
spec:
  selector:
    app: netflix-app
  type: NodePort   # You can use LoadBalancer if in cloud
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 3000 # Pod container port
      nodePort: 30036 # Kubernetes will expose this on the node’s IP
