apiVersion: v1
kind: Service
metadata:
  name: netflix-service
spec:
  type: NodePort
  selector:
    app: netflix
  ports:
    - port: 80          # container port inside pod
      targetPort: 80    # container port inside pod
      nodePort: 30805   # Kubernetes NodePort, must be in 30000-32767 range
